### ISSUE TITLE
error after having been working with 0.0.13beta

### ISSUE THREAD

**Issue by carlituxman** [8none1/lednetwf_ble#35] opened 2024-12-25 10:42 UTC
It was running perfect with de beta 0.0.13, but now has error:

Registrador: homeassistant.config_entries
Fuente: config_entries.py:640
Ocurrió por primera vez: 11:27:03 (1 ocurrencias)
Última vez registrado: 11:27:03

Error setting up entry LEDnet Cocina for lednetwf_ble
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/__init__.py", line 22, in async_setup_entry
    instance   = LEDNETWFInstance(entry.data[CONF_MAC], hass, config, options)
  File "/config/custom_components/lednetwf_ble/lednetwf.py", line 178, in __init__
    self._model_interface = model_class(service_info['manufacturer_data'])
                            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/models/model_0x56.py", line 45, in __init__
    LOGGER.debug(f"Manu data: {[hex(x) for x in self.manu_data]}")
                                ~~~^^^
TypeError: 'str' object cannot be interpreted as an integer

**Comment by 8none1** [comment] 2024-12-28 10:50
I can't understand how this error is being triggered.

Are you still running the beta release or did you download a different version?

Please try to remove the device and re-add it.

**Comment by 8none1** [comment] 2024-12-28 14:03
... maybe I found the bug actually.

**Comment by carlituxman** [comment] 2024-12-29 10:42
> I can't understand how this error is being triggered.
> 
> 
> 
> Are you still running the beta release or did you download a different version?
> 
> 
> 
> Please try to remove the device and re-add it.
> 
> 

I removed and just added and working

**Comment by 8none1** [comment] 2024-12-29 11:08
Excellent!  I did find a bug as well, which may have been the root cause of this.  Glad it's working.  Closing this issue now, feel free to open more if you find new problems.

Hoping to make a full release in the next week.

**Closed by 8none1** 2024-12-29 11:08 UTC
